### ISSUE TITLE
Strange characters in PDF example 30.1: Makefile

### ISSUE THREAD

**Issue by debaze** [twoscoops/two-scoops-of-django-1.11#67] opened 2017-06-07 12:53 UTC
## Location within the Book

* 30: Deployment: Platforms as a Service
* 30.2: Best practices for deployment to PaaS
* 3.2.4: Multiple requirements Files in Multiple Environments

Example 30.1: Makefile for Multiple Requirements Files

## Description 

Makefile examples displays ^^I
I suppose these should be tabs?

Used PDF reader: Okular 0.20.2 - KDE development platform  4.14.2
 3.16.0-38-generic #52~14.04.1-Ubuntu SMP

See screenshot attached:

![scoops_strange_chars](https://user-images.githubusercontent.com/7274897/26879127-36d259ec-4b90-11e7-8f92-3c864e6de78a.jpeg)

```
# Makefile
deploystaging:
^^Iecho -r requirements/staging.txt > requirements.txt
^^Igit commit -am "Requirements change for staging deployment"
^^Igit push heroku master
 # For heroku or other 'git push' deployments
^^Ieb deploy
 # For Elastic Beanstalk or other command deployments
^^Iecho -r requirements/production.txt > requirements.txt
^^Igit commit -am "Change back to production requirements"

```

**Comment by pydanny** [comment] 2017-06-09 18:23
Duplicate of #61

**Closed by pydanny** 2017-06-09 18:23 UTC
